import_schedule:
  name: Import AI Schedule
  description: Import or update the AI-generated schedule for devices.
  fields:
    schedule_json:
      name: Schedule JSON
      description: The JSON schedule, validated against schema.json
      required: true
      example: "{...}"

cleanup_removed:
  name: Cleanup Removed Devices
  description: Remove all entities and calendars for devices no longer present in the schedule.
