validate_schedule:
  name: Validate Schedule
  description: |
    Validates the provided JSON schedule structure without applying it.
  fields:
    schedule:
      name: Schedule JSON
      description: The raw JSON string to validate.
      required: true
      example: '{"heat_pump": {"schedule": [{"start": "2025-06-02T00:00:00+02:00", "end": "2025-06-02T01:00:00+02:00", "command": "heat"}]}}'
      selector:
        text:

update_schedule:
  name: Update Schedule
  description: |
    Updates the current schedule and devices using the provided JSON data.
  fields:
    schedule:
      name: Schedule JSON
      description: The raw JSON string defining all devices and their schedules.
      required: true
      example: '{"heat_pump": {"schedule": [{"start": "2025-06-02T00:00:00+02:00", "end": "2025-06-02T01:00:00+02:00", "command": "heat"}]}}'
      selector:
        text:

cleanup_removed:
  name: Cleanup Removed Devices
  description: |
    Removes any sensors and calendars for devices not found in the latest schedule.
  fields: {}
