name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hassfest:
    name: Run hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Home Assistant and Requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install homeassistant
      - name: Run hassfest
        run: |
          hassfest --config .

  hacs-validation:
    name: Run HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install HACS Validator
        run: npm install -g @hacs/validate
      - name: Run HACS validate
        run: |
          validate

  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

