name: Create Release Draft

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release Draft
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip component
        run: |
          zip -r ai_energy_scheduler.zip custom_components/ai_energy_scheduler

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: ai_energy_scheduler.zip