name: Test and Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff jsonschema
      - name: Lint Python
        run: |
          black --check .
          isort --check .
          ruff .

  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate example_schedule.json
        run: |
          pip install jsonschema
          python3 -c "import json, jsonschema; schema=json.load(open('ai_energy_scheduler/schema.json')); data=json.load(open('ai_energy_scheduler/example_schedule.json')); jsonschema.validate(instance=data, schema=schema)"

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master